# -*- coding: utf-8 -*-
"""
Verification script: recomputation of the η² effect size for the S6 random-control / trained-model Kruskal-Wallis tests
=====================================================================
Data sources (archived JSON in the package; authoritative):
  - reference_results/gradcam_v3/random_init_control/random_init_statistical_results.json
    (random-initialisation control, generated by run_random_init_gradcam_control.py)
  - reference_results/gradcam_v3/statistical_results.json
    (trained model, generated by run_gradcam_confusion_aggregate_v3.py)

η² uses the standard effect-size formula for the Kruskal-Wallis test (Tomczak & Tomczak, 2014):
    η² = H / (n - 1)
where n is the combined sample size of the three groups (for this test set n=144, 48 each for CN/MCI/AD).

⚠ Version-history note (important):
  Paper v27 reported this set of statistics in S6 (under the definition used at the time, H=6.12/16.75);
  since the length reduction for v60, **the paper's main text and supplementary materials no longer contain this set of numbers**
  (a full-text search of the manuscript finds 0 occurrences of "6.12"/"16.75"), and the formal statement of between-group CAM differences
  was changed to the between-group comparison of MTL mass fractions and the occlusion experiment (paper §3.3 / S6).
  This script therefore no longer compares against "paper values", but instead verifies the **internal consistency of the archived JSON**:
  ① the recomputation of the η² = H/(n-1) formula agrees digit for digit with the eta_squared embedded in the JSON;
  ② the direction of the p value agrees with the JSON record;
  ③ the sample size n=144 agrees with the per-group counts.
  The archived JSON was generated by the original experiment scripts in the 05/28 directory and frozen; it is the only authoritative source for this set of statistics.

Usage:
  python stats_rechecks/gradcam_kw_eta2_recheck.py
  (exit code 0 = all checks passed)
"""
import json
import os
import sys
from pathlib import Path

# A Chinese-locale Windows console defaults to GBK; this script prints characters such as η², so the encoding error strategy must be relaxed
for _s in (sys.stdout, sys.stderr):
    try:
        _s.reconfigure(errors="replace")
    except Exception:
        pass

HERE = Path(__file__).resolve().parent
RESULTS_DIR = HERE.parent / "reference_results" / "gradcam_v3"

N_TEST = 144  # test-set sample size (48 each for CN/MCI/AD), consistent with n_total in random_init_statistical_results.json


def eta_squared(h: float, n: int) -> float:
    """Kruskal-Wallis effect size: η² = H/(n-1) (Tomczak & Tomczak, 2014)"""
    return h / (n - 1)


def main():
    random_json = json.loads(
        (RESULTS_DIR / "random_init_control" / "random_init_statistical_results.json").read_text(encoding="utf-8"))
    trained_json = json.loads((RESULTS_DIR / "statistical_results.json").read_text(encoding="utf-8"))

    rows = []
    for label, data in [
        ("random-initialisation control", random_json),
        ("trained model", trained_json),
    ]:
        kw = data["kruskal_mtl_across_groups"]
        n_total = data.get("n_total", kw.get("n"))
        rows.append((label, kw, n_total))

    print("=" * 72)
    print("S6 KW η² recomputation (benchmark = archived JSON; the manuscript no longer contains this set of statistics)")
    print("=" * 72)
    all_ok = True
    for label, kw, n_total in rows:
        h, p = kw["H"], kw["p_value"]
        e2_json = kw.get("eta_squared")
        e2 = eta_squared(h, n_total)
        # assertion ①: the recomputed η² formula agrees with the value embedded in the JSON
        ok_e = (e2_json is not None) and abs(e2 - e2_json) < 1e-9
        # assertion ②: plausibility of the direction of the p value and of H (for H>0, p should be far below 1)
        ok_p = (0.0 < p < 1.0) and ((p < 0.01) if h > 5 else True)
        # assertion ③: sample sizes agree
        ok_n = (n_total == N_TEST)
        all_ok &= ok_e and ok_p and ok_n
        p_str = f"{p:.6g}"
        print(f"\n[{label}]  n_total={n_total}")
        print(f"  H            = {h:.6f}")
        print(f"  p            = {p_str}")
        print(f"  η²(embedded in JSON) = {e2_json:.9f}" if e2_json is not None else "  η²(embedded in JSON) = missing")
        print(f"  η²(recomputed) = {e2:.9f}   {'OK' if ok_e else 'MISMATCH'}")
        print(f"  p direction / sample size   {'OK' if (ok_p and ok_n) else 'MISMATCH'}")
    print("\n" + ("[all passed] The H, p and η² in the archived JSON are internally consistent (η²=H/(n-1)) and"
                  " traceable to the original experiments in the 05/28 directory."
                  if all_ok else "[inconsistency found] please check the MISMATCH items above."))
    return 0 if all_ok else 1


if __name__ == "__main__":
    raise SystemExit(main())
