# -*- coding: utf-8 -*-
"""Controlled baselines (paper §2.7 / §3.5 / supplementary S9) — fitting, evaluation and statistical testing.

Input `structural_panel.csv` (generated by extract_structural_panel_s9.py); outputs every
value in paper Tables 3 / 4 and supplementary S9.4.

================================================================================
[baseline definitions]
================================================================================
  B1  Age + sex                   logistic regression   Demographic floor baseline (doubles as the
                                                        "performance is not demographic leakage" negative control)
  B2  Structural measurement panel (6)   logistic regression   Representative of regional-volume approaches
  B3  Structural measurement panel (6)   RBF-SVM               Non-linear counterpart of the above
  B4  Structural panel + age/sex (8)     logistic regression   Tests whether demographics add information
  B5  Structural panel + age/sex (8)     RBF-SVM

  The 6 structural measurements = gmr_hippocampus_700, gmr_amygdala_700, gmr_parahippocampal_700,
                gmr_mtl_700, vmr_latventricle, brain_gm_ml

  Both families of baselines **use only the same input modality as the main model** (a single
  T1-weighted sMRI) and the same preprocessing pipeline, with no PET, CSF or cognitive scores —
  a strictly same-source comparison.

================================================================================
[evaluation protocol (identical to the main model)]
================================================================================
  · Main results: fitted on the 810 non-test subjects → a single evaluation on the 144-subject
    fixed test set (48 per class)
  · Standardisation: StandardScaler fitted on the training set only (guaranteed by make_pipeline)
  · Hyperparameters: LR C=1.0 / max_iter=5000; RBF-SVM C=1.0 / gamma='scale' (Platt probability calibration)
            **no hyperparameter search whatsoever** → the results are a lower-bound reference for this family of methods
  · 95% CI: 2000 stratified bootstrap resamples (sampled with replacement within each true class,
    then concatenated), percentile method
  · Difference test: 2000 **paired** stratified bootstrap resamples, two-sided empirical p
    (resolution floor 1/2000 = 0.0005)
  · 5-fold control: reuses the main model's StratifiedKFold(5, shuffle=True, random_state=42)
  · External cohorts: the model fitted on ADNI is extrapolated **zero fine-tuning**; MIRIAD uses P(AD),
              OASIS-2 uses P(AD)/[P(AD)+P(CN)] (the external cohorts lack demographics, hence the 6-measurement structural panel only)

  Global random seed 42; the bootstrap uses np.random.default_rng(42).

Run:
    python baselines/run_baselines.py
"""
import os
import io
import sys
import json

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import roc_auc_score, accuracy_score, f1_score

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import load_config, resolve_path, resolve_with_archive  # noqa: E402

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", line_buffering=True)

rng = np.random.default_rng(42)
N_BOOT = 2000
LABEL_MAP = {0.0: 0, 0.5: 1, 1.0: 2}     # CN / MCI / AD

# the 6 structural measurements (τ=700 main definition)
VOL_FEATS = ["gmr_hippocampus_700", "gmr_amygdala_700", "gmr_parahippocampal_700",
             "gmr_mtl_700", "vmr_latventricle", "brain_gm_ml"]
DEMO_FEATS = ["age", "sex_m"]


# ---------------------------------------------------------------------------
# data loading
# ---------------------------------------------------------------------------
def load_all(cfg):
    panel_p = resolve_with_archive(cfg, "structural_panel.csv")
    panel = pd.read_csv(panel_p)
    print(f"[data] structural_panel.csv {panel.shape}  cohort {panel.cohort.value_counts().to_dict()}")

    # Demographics: ADNI subject list (with Image Data ID / Age / Sex)
    # Note: the image-list Excel holds only file_path/label; demographics need a separate table (see config data.adni_demo)
    demo_p = resolve_path(cfg, "data.adni_demo")
    demo = pd.read_excel(demo_p)
    if "Age" not in demo.columns or "Sex" not in demo.columns:
        raise KeyError(f"{demo_p} must contain the Age and Sex columns (used for B1/B4/B5)")
    demo["Image Data ID"] = demo["Image Data ID"].astype(str).str.strip()

    a = panel[panel.cohort == "ADNI"].copy()
    # subject looks like "ADNI-2093_xxx" → take the prefix as the Image Data ID
    a["Image Data ID"] = a.subject.astype(str).str.split("_").str[0]
    a = a.merge(demo[["Image Data ID", "Age", "Sex"]], on="Image Data ID", how="left")
    miss = int(a.Age.isna().sum())
    print(f"[demographics] missing age after the ADNI merge {miss}/{len(a)}")
    assert miss == 0, "missing age; the Image Data ID concatenation rule needs checking"
    a["age"] = a.Age.astype(float)
    a["sex_m"] = (a.Sex == "M").astype(int)

    # fixed test set of 144 subjects (identical to the main model)
    fs = json.load(open(resolve_path(cfg, "data.fixed_split"), encoding="utf-8"))
    test_stems = {os.path.basename(x["file_path"]).replace("_ws.nii.gz", "")
                  for x in fs["test_split"]}
    print(f"[split] fixed test set {len(test_stems)} subjects")
    return panel, a, test_stems


# ---------------------------------------------------------------------------
# metrics
# ---------------------------------------------------------------------------
def macro_auc(y, P):
    return float(np.mean([roc_auc_score((y == k).astype(int), P[:, k]) for k in range(3)]))


def metrics(y, P):
    pred = P.argmax(1)
    out = {"acc": float(accuracy_score(y, pred)),
           "macro_f1": float(f1_score(y, pred, average="macro")),
           "macro_auc": macro_auc(y, P)}
    for k in range(3):
        out[f"auc_c{k}"] = float(roc_auc_score((y == k).astype(int), P[:, k]))
    return out


def fit_predict(kind, Xtr, ytr, Xte):
    """Standardisation + classifier (standardisation fitted on the training set only, to avoid leakage)."""
    if kind == "lr":
        clf = LogisticRegression(max_iter=5000, C=1.0, random_state=42)
    elif kind == "svm":
        clf = SVC(kernel="rbf", C=1.0, gamma="scale", probability=True, random_state=42)
    else:
        raise ValueError(kind)
    m = make_pipeline(StandardScaler(), clf)
    m.fit(Xtr, ytr)
    return m.predict_proba(Xte)


def strat_boot_idx(y):
    """Stratified bootstrap: sample with replacement within each true class, then concatenate."""
    idx = []
    for k in np.unique(y):
        kk = np.where(y == k)[0]
        idx.append(rng.choice(kk, size=len(kk), replace=True))
    return np.concatenate(idx)


# ---------------------------------------------------------------------------
# main flow
# ---------------------------------------------------------------------------
def main():
    cfg = load_config()
    out = cfg["output_dir"]
    os.makedirs(out, exist_ok=True)

    panel, adni, test_stems = load_all(cfg)
    adni["is_test"] = adni.subject.isin(test_stems)

    tr_all = adni[~adni.is_test].reset_index(drop=True)
    y_all = tr_all.label.map(LABEL_MAP).values
    te = adni[adni.is_test].reset_index(drop=True)
    y_te = te.label.map(LABEL_MAP).values
    print(f"[train] n={len(tr_all)}   [test] n={len(te)} "
          f"classes {pd.Series(y_te).value_counts().sort_index().to_dict()}")

    # the 5-fold split reuses the main model's definition (identical to train/train_5fold.py)
    skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
    ref_folds = [va for _, va in skf.split(np.zeros(len(y_all)), y_all)]
    print(f"[5-fold] validation-set size of each fold in the 810-subject split {[len(f) for f in ref_folds]}")

    BASELINES = {
        "B1 age+sex LR": (DEMO_FEATS, "lr"),
        "B2 structural panel LR": (VOL_FEATS, "lr"),
        "B3 structural panel SVM": (VOL_FEATS, "svm"),
        "B4 panel+demo LR": (VOL_FEATS + DEMO_FEATS, "lr"),
        "B5 panel+demo SVM": (VOL_FEATS + DEMO_FEATS, "svm"),
    }

    # ---- main results: fit on 810 subjects → 144-subject fixed test set ----
    print("\n[main results: 144-subject fixed test set]")
    rows, probs = [], {}
    for name, (feats, kind) in BASELINES.items():
        P = fit_predict(kind, tr_all[feats].values, y_all, te[feats].values)
        m = metrics(y_te, P)
        probs[name] = P
        rows.append({"baseline": name, **m, "n_features": len(feats)})
        print(f"  {name:<30} Acc={m['acc']:.4f}  macroF1={m['macro_f1']:.4f}  "
              f"macroAUC={m['macro_auc']:.4f}")

    # ---- stratified bootstrap 95% CI ----
    for r in rows:
        P = probs[r["baseline"]]
        bs = np.array([metrics(y_te[i], P[i])["macro_auc"]
                       for i in (strat_boot_idx(y_te) for _ in range(N_BOOT))])
        r["macro_auc_ci_lo"] = float(np.percentile(bs, 2.5))
        r["macro_auc_ci_hi"] = float(np.percentile(bs, 97.5))

    # ---- paired bootstrap difference against the ensemble model ----
    ens = pd.read_csv(resolve_path(cfg, "data.pred_csv"))
    cmap = {os.path.basename(p).replace("_ws.nii.gz", ""): i
            for i, p in enumerate(ens.file_path)}
    order = [cmap[s] for s in te.subject]
    Pe = ens[["prob_cn", "prob_mci", "prob_ad"]].values[order]
    y_e = ens.true_label.values[order]
    assert (y_e == y_te).all(), "the ensemble predictions and the structural panel disagree on sample order/labels"
    m_e = metrics(y_te, Pe)
    print(f"\n[ensemble] Acc={m_e['acc']:.4f}  macroF1={m_e['macro_f1']:.4f}  "
          f"macroAUC={m_e['macro_auc']:.4f}")

    d_obs = m_e["macro_auc"] - np.array([r["macro_auc"] for r in rows])
    boot_d = np.array([
        [macro_auc(y_te[i], Pe[i]) - macro_auc(y_te[i], probs[r["baseline"]][i]) for r in rows]
        for i in (strat_boot_idx(y_te) for _ in range(N_BOOT))
    ])
    for j, r in enumerate(rows):
        r["delta_vs_cnn"] = float(d_obs[j] * 100)
        r["delta_ci_lo"] = float(np.percentile(boot_d[:, j], 2.5) * 100)
        r["delta_ci_hi"] = float(np.percentile(boot_d[:, j], 97.5) * 100)
        p = 2 * min((boot_d[:, j] <= 0).mean(), (boot_d[:, j] >= 0).mean())
        r["p_paired"] = float(max(p, 1.0 / N_BOOT))

    pd.DataFrame(rows).to_csv(os.path.join(out, "baseline_test_set_performance.csv"),
                              index=False, encoding="utf-8-sig")
    pd.DataFrame([{"baseline": "CNN 5-fold ensemble", **m_e}]).to_csv(
        os.path.join(out, "cnn_ensemble_test_set_performance.csv"),
        index=False, encoding="utf-8-sig")

    print(f"\n{'baseline':<30}{'Acc':>8}{'F1':>8}{'AUC':>8}{'95% CI':>20}{'ΔAUC':>9}{'p':>9}")
    print("-" * 100)
    print(f"{'CNN 5-fold ensemble':<30}{m_e['acc']:>8.4f}{m_e['macro_f1']:>8.4f}"
          f"{m_e['macro_auc']:>8.4f}")
    for r in rows:
        print(f"{r['baseline']:<30}{r['acc']:>8.4f}{r['macro_f1']:>8.4f}{r['macro_auc']:>8.4f}"
              f"  [{r['macro_auc_ci_lo']:.4f},{r['macro_auc_ci_hi']:.4f}]"
              f"{r['delta_vs_cnn']:>+9.1f}{r['p_paired']:>9.4f}")

    # ---- 5-fold cross-validation (reusing the main model's split) ----
    print("\n[5-fold cross-validation]")
    cv_rows = []
    for name, (feats, kind) in BASELINES.items():
        aucs = []
        for tr_i, va_i in skf.split(np.zeros(len(y_all)), y_all):
            P = fit_predict(kind, tr_all.iloc[tr_i][feats].values, y_all[tr_i],
                            tr_all.iloc[va_i][feats].values)
            aucs.append(macro_auc(y_all[va_i], P))
        cv_rows.append({"baseline": name, "AUC_mean": float(np.mean(aucs)),
                        "AUC_sd": float(np.std(aucs, ddof=1)),
                        "AUC_min": float(np.min(aucs)), "AUC_max": float(np.max(aucs)),
                        "folds": ";".join(f"{a:.4f}" for a in aucs)})
        print(f"  {name:<30} AUC={np.mean(aucs):.4f}±{np.std(aucs, ddof=1):.4f}")
    pd.DataFrame(cv_rows).to_csv(os.path.join(out, "baseline_5fold_cv.csv"),
                                 index=False, encoding="utf-8-sig")

    # ---- external cohorts: zero-fine-tuning extrapolation of the structural panel (no demographics) ----
    print("\n[external cohorts: zero-fine-tuning extrapolation of the structural panel]")
    ext_rows = []
    for cohort, tag in [("MIRIAD", "MIRIAD"), ("OASIS2", "OASIS-2")]:
        sub = panel[panel.cohort == cohort].copy()
        if sub.empty:
            print(f"  {tag}: no data, skipping")
            continue
        P = fit_predict("lr", tr_all[VOL_FEATS].values, y_all, sub[VOL_FEATS].values)
        lab = sub.label.values
        if cohort == "MIRIAD":
            auc = roc_auc_score((lab == 1.0).astype(int), P[:, 2])
            ext_rows.append({"cohort": cohort, "n": len(sub), "view": "AD vs HC (P(AD))",
                             "baseline": "B2 structural panel LR", "AUC": float(auc)})
            print(f"  {tag}: AD vs HC  AUC={auc:.4f}  n={len(sub)}")
        else:
            keep = lab != 0.5
            s = P[keep, 2] / (P[keep, 2] + P[keep, 0])
            auc = roc_auc_score((lab[keep] == 1.0).astype(int), s)
            ext_rows.append({"cohort": cohort, "n": int(keep.sum()), "view": "CN vs AD",
                             "baseline": "B2 structural panel LR", "AUC": float(auc)})
            print(f"  {tag}: CN vs AD   AUC={auc:.4f}  n={int(keep.sum())}")
    if ext_rows:
        pd.DataFrame(ext_rows).to_csv(os.path.join(out, "baseline_external_cohorts.csv"),
                                      index=False, encoding="utf-8-sig")

    print(f"\nDone -> {out}")


if __name__ == "__main__":
    main()
